version: '2'

services:
    nextcloud:
        image: dch/nextcloud
        container_name: nextcloud
        restart: unless-stopped
        network_mode: "bridge"
        environment:
            - DB_NAME=nextcloud
            - DB_PASS=nextcloud
            - DB_USER=nextcloud
        volumes:
            - ./vol/html/apps:/var/www/html/apps/
            - ./vol/html/config:/var/www/html/config/
            - ./vol/html/data:/var/www/html/data/
            - ./vol/database:/var/lib/mysql_data/
        ports:
            - "8080:80"
        tty: true
