version: "3"

services:
    nextcloud:
        build:
            context: .
            dockerfile: dockerfile
        image: dch/nextcloud
        container_name: nextcloud
        hostname: nextcloud
        restart: unless-stopped
        network_mode: "bridge"
        environment:
            - DB_NAME=nextcloud
            - DB_PASS=nextcloud
            - DB_USER=nextcloud
            - APACHE_LOG_DIR=/var/log/apache2/
            - NC_FQDN=<Set_FQDN_HERE>
        volumes:
            - ./vol/nextcloud/apps:/var/www/nextcloud/apps/
            - ./vol/nextcloud/config:/var/www/nextcloud/config/
            - ./vol/nextcloud/data:/var/www/nextcloud/data/
            - ./vol/database:/var/lib/mysql_data/
        ports:
            - "8080:80"
        tty: true
        

